export const BUILD={version:'v103',name:'Reports & Month Navigator',storageKey:'gringottsBudgetVault.latest',runtime:'src/runtime-v103-reports-month.js',cacheBust:'103reports1'};
export const RULE_KEY='gringottsRulesIII.preview.v1',CASHFLOW_KEY='gringottsCashflowManual.v1',MONTH_KEY='gringottsCleanMonth.v1';
export const $=id=>document.getElementById(id);
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const xml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export const num=value=>Number.isFinite(Number(value))?Number(value):0;
export const money=value=>num(value).toLocaleString(undefined,{style:'currency',currency:'USD'});
export const stamp=()=>new Date().toISOString().replace(/[:.]/g,'-');
export const uid=prefix=>prefix+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);
export function read(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
export function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
export function keys(){try{return Object.keys(localStorage).sort()}catch{return[]}}
export function vaults(){return keys().filter(key=>key.startsWith('gringottsBudgetVault.')&&key!=='gringottsBudgetVault.meta').map(key=>{try{const raw=localStorage.getItem(key)||'',obj=JSON.parse(raw),transactions=Array.isArray(obj.transactions)?obj.transactions.length:0,last=Date.parse(obj.lastSavedAt||obj.restoredAt||obj.updatedAt||obj.createdAt||0)||0;return{key,obj,bytes:raw.length,transactions,last,status:'readable'}}catch{return{key,obj:null,bytes:0,transactions:0,last:0,status:'error'}}}).sort((a,b)=>b.transactions-a.transactions||b.last-a.last)}
export const best=()=>vaults()[0]||null;
export function state(){const candidate=best();return candidate?.obj?{...candidate.obj,transactions:Array.isArray(candidate.obj.transactions)?candidate.obj.transactions:[],_activeKey:candidate.key}:{transactions:[],_activeKey:'none'}}
export const txs=()=>state().transactions||[];
export const dte=t=>String(t.date||t.posted_datetime||t.authorized_date||t.datetime||'').slice(0,10);
export const txName=t=>t.merchant||t.merchant_name||t.name||t.description||'Unknown';
export const category=t=>t.category||t.personal_finance_category_primary||t.primaryCategory||'Other';
export const account=t=>t.account||t.accountName||t.account_name||t.official_name||t.account_id||'';
export const owner=t=>t.owner||t.cardOwner||t.cardLast4||t.account_owner||'Unassigned';
export const txText=t=>[txName(t),category(t),account(t),owner(t),t.description,t.category_detailed,t.personal_finance_category_detailed].join(' ').toLowerCase();
export const monthOf=t=>{const date=dte(t);return date&&date.length>=7?date.slice(0,7):''};
export const months=()=>[...new Set(txs().map(monthOf).filter(Boolean))].sort();
export const validMonth=value=>/^\d{4}-\d{2}$/.test(String(value||''));
let selectedMonth=localStorage.getItem(MONTH_KEY)||'';
export function getMonth(){if(!validMonth(selectedMonth)){const available=months();selectedMonth=available.at(-1)||new Date().toISOString().slice(0,7)}localStorage.setItem(MONTH_KEY,selectedMonth);return selectedMonth}
export function setMonthValue(value){if(!validMonth(value))return false;selectedMonth=value;localStorage.setItem(MONTH_KEY,value);return true}
export function shiftMonth(yearMonth,delta){const match=String(yearMonth||'').match(/^(\d{4})-(\d{2})$/),date=match?new Date(Number(match[1]),Number(match[2])-1+delta,1):new Date();return date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')}
export function monthLabel(yearMonth){const match=String(yearMonth||'').match(/^(\d{4})-(\d{2})$/);return match?new Date(Number(match[1]),Number(match[2])-1,1).toLocaleDateString(undefined,{month:'long',year:'numeric'}):String(yearMonth||'No month')}
export const rowsForMonth=yearMonth=>txs().filter(t=>monthOf(t)===yearMonth);
export const isPending=t=>t.pending===true||String(t.status||'').toLowerCase()==='pending';
export function isTransfer(t){const cats=[category(t),t.category_detailed,t.personal_finance_category_primary,t.personal_finance_category_detailed].join(' ').toLowerCase();if(/transfer|internal movement/.test(cats))return true;return /\btransfer (to|from)\b|internal transfer|payment thank you/.test(txText(t))&&/transfer|payment/.test(cats)}
export function flow(t){const explicit=String(t.type||t.flow_type||t.transaction_type||'').toLowerCase();if(isTransfer(t))return'Transfer';if(/income|deposit|inflow|credit/.test(explicit))return'Income';if(/expense|outflow|debit|purchase/.test(explicit))return'Expense';return num(t.amount)<0?'Income':'Expense'}
export const reportAmount=t=>Math.abs(num(t.amount));
export function metrics(yearMonth){const rows=rowsForMonth(yearMonth);let income=0,spend=0,transfers=0,cashOut=0,pending=0;rows.forEach(t=>{const amount=reportAmount(t);if(isPending(t))pending++;if(flow(t)==='Income')income+=amount;else if(flow(t)==='Transfer')transfers+=amount;else spend+=amount;if(num(t.amount)>0)cashOut+=amount});const review=rows.filter(t=>{const c=String(category(t)).toLowerCase();return t.reviewed===false||c==='uncategorized'||c==='other'||!c}).length;return{income,spend,transfers,cashOut,net:income-spend,count:rows.length,pending,review}}
function sumBy(rows,keyFn,includeFn){const map=new Map;rows.forEach(t=>{if(includeFn&&!includeFn(t))return;const key=String(keyFn(t)||'Unknown');map.set(key,(map.get(key)||0)+reportAmount(t))});return[...map.entries()].sort((a,b)=>b[1]-a[1])}
export const categoryTotals=month=>sumBy(rowsForMonth(month),category,t=>flow(t)==='Expense');
export const merchantTotals=month=>sumBy(rowsForMonth(month),txName,t=>flow(t)==='Expense');
export const accountOwnerTotals=month=>sumBy(rowsForMonth(month),t=>{const a=account(t),o=owner(t);return o==='Unassigned'?(a||'Unassigned'):o+(a?' — '+a:'')},t=>flow(t)==='Expense');
export function categoryMovers(month){const prior=shiftMonth(month,-1),current=new Map(categoryTotals(month)),previous=new Map(categoryTotals(prior));return[...new Set([...current.keys(),...previous.keys()])].map(c=>({category:c,current:current.get(c)||0,previous:previous.get(c)||0,delta:(current.get(c)||0)-(previous.get(c)||0)})).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta))}
export function ytdMetrics(month){const year=String(month).slice(0,4);let income=0,spend=0,transfers=0;txs().forEach(t=>{if(!dte(t).startsWith(year+'-'))return;const amount=reportAmount(t);if(flow(t)==='Income')income+=amount;else if(flow(t)==='Transfer')transfers+=amount;else spend+=amount});return{income,spend,transfers,net:income-spend}}
export function recurringCandidates(){const grouped=new Map;txs().forEach(t=>{if(flow(t)!=='Expense')return;const key=String(txName(t)).toLowerCase().replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').trim();if(!key)return;const list=grouped.get(key)||[];list.push(t);grouped.set(key,list)});return[...grouped.values()].map(rows=>{const distinct=[...new Set(rows.map(monthOf).filter(Boolean))],amounts=rows.map(reportAmount).filter(v=>v>0),average=amounts.reduce((s,v)=>s+v,0)/(amounts.length||1),range=amounts.length?Math.max(...amounts)-Math.min(...amounts):0;return{name:txName(rows[0]),category:category(rows[0]),account:account(rows[0]),occurrences:rows.length,months:distinct.length,average,range,latest:rows.map(dte).sort().at(-1)||''}}).filter(x=>x.months>=2&&x.occurrences>=2&&(x.average===0||x.range<=Math.max(5,x.average*.25))).sort((a,b)=>b.months-a.months||b.average-a.average).slice(0,50)}
export function executiveSummary(month){const current=metrics(month),priorMonth=shiftMonth(month,-1),prior=metrics(priorMonth),ytd=ytdMetrics(month),categories=categoryTotals(month),movers=categoryMovers(month),eating=categories.find(([c])=>/eating out|dining|restaurant/i.test(c))?.[1]||0,change=current.spend-prior.spend,top=categories[0],up=movers.find(x=>x.delta>0),down=movers.find(x=>x.delta<0),coverage=rowsForMonth(month).map(dte).filter(Boolean).sort();return[`${monthLabel(month)} includes ${current.count} transactions with ${money(current.income)} of income, ${money(current.spend)} of household spending, and a household net of ${money(current.net)}.`,prior.count?`Spending was ${change>=0?money(change)+' higher':money(Math.abs(change))+' lower'} than ${monthLabel(priorMonth)}.`:`There is no prior-month transaction set available for comparison with ${monthLabel(priorMonth)}.`,`Year-to-date household income is ${money(ytd.income)}, spending is ${money(ytd.spend)}, and net is ${money(ytd.net)}.`,top?`The largest spending category was ${top[0]} at ${money(top[1])}.`:'No household spending categories were recorded for this month.',eating?`Eating out totaled ${money(eating)}.`:'No eating-out spending was identified for this month.',up?`${up.category} increased the most, up ${money(up.delta)} from the prior month.`:'',down?`${down.category} decreased the most, down ${money(Math.abs(down.delta))} from the prior month.`:'',current.transfers?`${money(current.transfers)} of transfers are shown separately and excluded from household spending.`:'',current.pending?`${current.pending} pending transaction${current.pending===1?'':'s'} should be treated as provisional.`:'',current.review?`${current.review} transaction${current.review===1?'':'s'} may need category or review cleanup before final reporting.`:'No obvious category/review warnings were detected in the selected month.',coverage.length?`Visible selected-month coverage runs from ${coverage[0]} through ${coverage.at(-1)}.`:`No transactions are stored for ${monthLabel(month)}.`].filter(Boolean).join(' ')}
export function meetingPack(month){const current=metrics(month),prior=metrics(shiftMonth(month,-1)),categories=categoryTotals(month),merchants=merchantTotals(month),movers=categoryMovers(month),wins=[],risks=[],actions=[];if(current.net>=0)wins.push(`Household income exceeded spending by ${money(current.net)}.`);if(prior.count&&current.spend<prior.spend)wins.push(`Spending decreased by ${money(prior.spend-current.spend)} from the prior month.`);if(!current.review)wins.push('No obvious review/category warnings were detected.');if(current.net<0)risks.push(`Household spending exceeded income by ${money(Math.abs(current.net))}.`);if(current.review)risks.push(`${current.review} transaction${current.review===1?'':'s'} need review or cleaner categories.`);if(current.pending)risks.push(`${current.pending} pending transaction${current.pending===1?'':'s'} may still change.`);if(movers[0]?.delta>0)risks.push(`${movers[0].category} increased by ${money(movers[0].delta)} versus the prior month.`);if(current.review)actions.push('Review uncategorized or unreviewed transactions before treating reports as final.');if(categories[0])actions.push(`Discuss whether ${categories[0][0]} at ${money(categories[0][1])} matched the family plan.`);if(current.transfers)actions.push('Confirm transfer/payment rows are excluded consistently from household-spending decisions.');if(!actions.length)actions.push('Choose one savings, debt, or family goal for the next month.');return{questions:[`Did ${monthLabel(month)} spending reflect our priorities?`,categories[0]?`Was ${categories[0][0]} intentionally our largest category?`:'Are any missing transactions or accounts expected?',merchants[0]?`Do we still want to spend about ${money(merchants[0][1])} with ${merchants[0][0]}?`:'Are there recurring purchases we should watch?','What one change would make next month easier?'],wins:wins.length?wins:['The monthly report is available for a family review.'],risks:risks.length?risks:['No major automatic risk flag was generated; still review the transaction detail.'],actions}}
export function reportWarnings(month){const m=metrics(month),out=[];if(!m.count)out.push('No transactions are stored for the selected month. Reports will contain headers and an empty-month notice only.');if(m.pending)out.push(`${m.pending} pending transaction${m.pending===1?'':'s'} are provisional.`);if(m.review)out.push(`${m.review} transaction${m.review===1?'':'s'} may need review or category cleanup.`);if(m.transfers)out.push(`${money(m.transfers)} of transfers are separated from household spending.`);return out}
export function download(name,body,type){const anchor=document.createElement('a'),blob=body instanceof Blob?body:new Blob([body],{type:type||'application/octet-stream'});anchor.href=URL.createObjectURL(blob);anchor.download=name;document.body.appendChild(anchor);anchor.click();setTimeout(()=>{URL.revokeObjectURL(anchor.href);anchor.remove()},0)}
export const downloadJson=(name,obj)=>download(name,JSON.stringify(obj,null,2),'application/json');
export function backup(notify=()=>{}){const candidate=best();if(!candidate?.obj||candidate.transactions<1){notify('No populated readable vault is available to back up');return false}downloadJson(`Gringotts_v103_backup_${candidate.transactions}_${stamp()}.json`,candidate.obj);notify('Current vault backup downloaded');return true}
export function ruleData(){const stored=read(RULE_KEY,{rules:[],createdAt:new Date().toISOString()}),rules=(Array.isArray(stored.rules)?stored.rules:[]).map((rule,index)=>({...rule,priority:Number.isFinite(Number(rule.priority))?Number(rule.priority):index+1})).sort((a,b)=>a.priority-b.priority);return{rules,createdAt:stored.createdAt||new Date().toISOString(),updatedAt:stored.updatedAt||''}}
export function saveRules(data){save(RULE_KEY,{rules:(data.rules||[]).map((rule,index)=>({...rule,priority:index+1})),createdAt:data.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()})}
export const enabledRules=()=>ruleData().rules.filter(rule=>rule.on!==false&&String(rule.find||'').trim()&&String(rule.to||'').trim());
const hay=(rule,t)=>(rule.scope==='name'?txName(t):rule.scope==='current'?category(t):rule.scope==='account'?account(t):txText(t)).toLowerCase();
export const matchesFor=t=>enabledRules().filter(rule=>hay(rule,t).includes(String(rule.find||'').toLowerCase()));
export function suggestions(){const output=[];txs().forEach((t,row)=>{const matches=matchesFor(t);if(!matches.length)return;const chosen=matches[0],from=category(t),to=chosen.to;if(from===to&&matches.length===1)return;output.push({row,date:dte(t),name:txName(t),amount:num(t.amount),from,to,chosenRule:chosen.label||chosen.find,matchCount:matches.length,allMatches:matches.map(rule=>({id:rule.id,label:rule.label||rule.find,to:rule.to,priority:rule.priority}))})});return output}
export const conflicts=()=>suggestions().filter(x=>x.matchCount>1);
export function reviewPackage(){return{generatedAt:new Date().toISOString(),runtime:BUILD,vault:{key:best()?.key||'none',transactions:txs().length},rules:{count:ruleData().rules.length,enabled:enabledRules().length},summary:{suggestions:suggestions().length,conflicts:conflicts().length},conflicts:conflicts(),suggestions:suggestions(),boundary:'v103 preserves rules preview and conflict review. It does not edit transaction rows.'}}
export const cashflow=()=>read(CASHFLOW_KEY,{bills:[],paydays:[]});
export const saveCashflow=value=>save(CASHFLOW_KEY,value);
export function calendarEvents(){const data=cashflow(),out=[];(data.bills||[]).forEach(x=>{if(x.dueDate)out.push({type:'bill',date:x.dueDate,title:x.name,amount:x.amount})});(data.paydays||[]).forEach(x=>{if(x.date)out.push({type:'payday',date:x.date,title:x.name,amount:x.amount})});return out.sort((a,b)=>a.date.localeCompare(b.date))}
export function ics(){const crlf='\r\n',generated=new Date().toISOString().replace(/[-:.]/g,'').slice(0,15)+'Z';return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Gringotts//v103//EN',...calendarEvents().flatMap((event,index)=>['BEGIN:VEVENT',`UID:v103-${index}@gringotts`,'DTSTAMP:'+generated,'DTSTART;VALUE=DATE:'+event.date.replaceAll('-',''),'SUMMARY:'+String(event.title).replace(/[;,]/g,' '),'DESCRIPTION:'+event.type+' '+money(event.amount),'END:VEVENT']),'END:VCALENDAR'].join(crlf)}
export function sourceLabel(vault){if(!vault||vault.source==null)return'Not provided';if(typeof vault.source==='string')return vault.source;if(typeof vault.source==='object')return vault.source.fileName||vault.source.institution||vault.source.version||vault.source.schema||'Metadata object present';return String(vault.source)}
export const shellProof=()=>{const loaded=window.GringottsCleanRuntime?.BUILD?.runtime||BUILD.runtime;return{title:document.title,expected:BUILD.runtime,loaded,ok:loaded===BUILD.runtime}};
export function debugReport(){return{runtime:BUILD,shellProof:shellProof(),selectedMonth:getMonth(),vault:{key:best()?.key||'none',transactions:txs().length,candidates:vaults().map(x=>({key:x.key,transactions:x.transactions,status:x.status}))},rules:{count:ruleData().rules.length,enabled:enabledRules().length,suggestions:suggestions().length,conflicts:conflicts().length},reports:{xlsxWriter:'bundled local OOXML/ZIP store writer',familyTracker:true,vaultWorkbook:true},privacy:'Local browser storage only. Imports and report generation run entirely in this browser.'}}
export async function serviceWorkerStatus(){let registrations=0,controller=false;try{if('serviceWorker'in navigator)registrations=(await navigator.serviceWorker.getRegistrations()).length;controller=Boolean(navigator.serviceWorker?.controller)}catch{}return{registrations,controller}}
