import{BUILD,account,accountOwnerTotals,best,calendarEvents,category,categoryTotals,download,dte,executiveSummary,flow,getMonth,meetingPack,merchantTotals,metrics,monthLabel,months,owner,recurringCandidates,reportAmount,reportWarnings,rowsForMonth,ruleData,sourceLabel,stamp,state,txName,ytdMetrics,isPending}from'./core.js';
import{xlsxBlob}from'./xlsx.js';
const csvSafe=value=>{const s=String(value??'');return/[",\n\r]/.test(s)?'"'+s.replaceAll('"','""')+'"':s};
export function familyTrackerCsv(month=getMonth()){const rows=rowsForMonth(month).slice().sort((a,b)=>dte(a).localeCompare(dte(b))||txName(a).localeCompare(txName(b)));return[['DATE','TYPE','CATEGORY','AMOUNT','DESCRIPTION'],...rows.map(t=>[dte(t),flow(t).toUpperCase(),category(t),reportAmount(t).toFixed(2),txName(t)])].map(row=>row.map(csvSafe).join(',')).join('\r\n')}
export function workbookSheets(month=getMonth()){const selected=rowsForMonth(month).slice().sort((a,b)=>dte(a).localeCompare(dte(b))),current=metrics(month),ytd=ytdMetrics(month),pack=meetingPack(month),monthly=months().map(value=>{const m=metrics(value);return[value,monthLabel(value),m.count,m.income,m.spend,m.transfers,m.net,m.pending,m.review]}),review=selected.filter(t=>{const c=String(category(t)).toLowerCase();return t.reviewed===false||c==='uncategorized'||c==='other'||!c}),vault=state(),candidate=best();return[
{name:'Executive Summary',rows:[['Gringotts Budget Vault','Executive Summary'],['Selected Month',monthLabel(month)],['Generated',new Date().toISOString()],['Summary',executiveSummary(month)],[],['Metric','Value'],['Transactions',current.count],['Income',current.income],['Household Spending',current.spend],['Transfers Separate',current.transfers],['Household Net',current.net],['Pending Rows',current.pending],['Review Warnings',current.review],['YTD Income',ytd.income],['YTD Spending',ytd.spend],['YTD Net',ytd.net],[],['Questions to Decide Together'],...pack.questions.map(v=>[v]),[],['Wins'],...pack.wins.map(v=>[v]),[],['Risks'],...pack.risks.map(v=>[v]),[],['Actions'],...pack.actions.map(v=>[v])]},
{name:'Transactions',rows:[['Date','Flow','Category','Amount','Description','Account','Owner Card','Pending','Reviewed','Source ID','Original Amount'],...selected.map(t=>[dte(t),flow(t),category(t),reportAmount(t),txName(t),account(t),owner(t),isPending(t)?'Yes':'No',t.reviewed===true?'Yes':'No',t.transaction_id||t.sourceId||t.id||'',Number(t.amount)||0])]},
{name:'Monthly Totals',rows:[['Month','Label','Transactions','Income','Household Spending','Transfers','Net','Pending','Review Warnings'],...monthly]},
{name:'Category Summary',rows:[['Category','Selected-Month Spending'],...categoryTotals(month)]},
{name:'Merchant Summary',rows:[['Merchant','Selected-Month Spending'],...merchantTotals(month).slice(0,250)]},
{name:'Account Owner Summary',rows:[['Owner / Account','Selected-Month Spending'],...accountOwnerTotals(month)]},
{name:'Recurring Charges',rows:[['Merchant','Category','Account','Occurrences','Distinct Months','Average Amount','Amount Range','Latest Date'],...recurringCandidates().map(x=>[x.name,x.category,x.account,x.occurrences,x.months,x.average,x.range,x.latest])]},
{name:'Bills Paydays',rows:[['Type','Date','Name','Amount'],...calendarEvents().map(x=>[x.type,x.date,x.title,x.amount])]},
{name:'Calendar Events',rows:[['Date','Event Type','Title','Amount'],...calendarEvents().map(x=>[x.date,x.type,x.title,x.amount])]},
{name:'Rules',rows:[['Priority','Label','Find','Suggested Category','Scope','Enabled'],...ruleData().rules.map(r=>[r.priority,r.label||'',r.find||'',r.to||'',r.scope||'all',r.on===false?'No':'Yes'])]},
{name:'Review Queue',rows:[['Date','Description','Category','Account','Amount','Reason'],...review.map(t=>[dte(t),txName(t),category(t),account(t),reportAmount(t),t.reviewed===false?'Not reviewed':'Category needs cleanup'])]},
{name:'Vault Metadata',rows:[['Field','Value'],['Runtime',BUILD.runtime],['Release',BUILD.version+' '+BUILD.name],['Selected Month',month],['Best Vault Key',candidate?.key||'none'],['Best Vault Transactions',candidate?.transactions||0],['Vault Version',vault.version||vault.appVersion||'Not provided'],['Source',sourceLabel(vault)],['Generated',new Date().toISOString()],['Privacy Boundary','Generated locally in the browser; transaction data is not uploaded.'],['Transfer Policy','Transfers are reported separately and excluded from household spending.'],['Pending Policy','Pending rows are included in transaction detail and flagged as provisional.']]}
]}
export function exportFamilyXlsx(notify=()=>{}){const month=getMonth(),rows=rowsForMonth(month).slice().sort((a,b)=>dte(a).localeCompare(dte(b))),sheets=[{name:'Transactions',rows:[['DATE','TYPE','CATEGORY','AMOUNT','DESCRIPTION'],...rows.map(t=>[dte(t),flow(t).toUpperCase(),category(t),reportAmount(t),txName(t)])]}];download(`Income_Expenses_Tracker_${month}_${stamp()}.xlsx`,xlsxBlob(sheets));notify(rows.length?'Family Tracker XLSX downloaded':'Empty-month Family Tracker XLSX downloaded')}
export function exportVaultXlsx(notify=()=>{}){const month=getMonth();download(`Gringotts_Budget_Vault_${month}_${stamp()}.xlsx`,xlsxBlob(workbookSheets(month)));notify('Vault Workbook XLSX downloaded')}
export function executiveMarkdown(month=getMonth()){const warnings=reportWarnings(month);return`# Gringotts Executive Summary — ${monthLabel(month)}\n\nGenerated: ${new Date().toISOString()}\n\n${executiveSummary(month)}\n\n## Report quality notes\n${warnings.length?warnings.map(v=>'- '+v).join('\n'):'- No automatic report-quality warnings detected.'}\n`}
export function meetingMarkdown(month=getMonth()){const pack=meetingPack(month),section=(title,values)=>`## ${title}\n${values.map(v=>'- '+v).join('\n')}\n`;return`# Gringotts Family Budget Meeting Pack — ${monthLabel(month)}\n\n${executiveSummary(month)}\n\n${section('Questions to Decide Together',pack.questions)}\n${section('Wins',pack.wins)}\n${section('Risks and Watch Items',pack.risks)}\n${section('Actions',pack.actions)}`}
export{xlsxBlob};
