(function(){
  const GBV=window.GBV;
  const alias={income:'Income',transfers:'Transfers',transfer:'Transfers',groceries:'Groceries',shopping:'Shopping',dining_drinks:'Dining',housing:'Housing',bills_utilities:'Utilities',transportation:'Transportation',pets:'Pets',health_wellness:'Health',education:'Education',entertainment:'Entertainment',financial:'Financial',gifts_donations:'Giving',other:'Other'};
  function money(n){return Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD'});}
  function normalizeCategory(raw){if(!raw) return 'Other'; const key=String(raw).trim().toLowerCase(); return alias[key]||String(raw).replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());}
  function txId(t,i){return t.transaction_id||t.id||`${t.date||t.datetime||t.posted_datetime||'date'}|${t.amount}|${t.merchant_name||t.name||'merchant'}|${i}`;}
  function normalizeTransaction(t,i){const amount=Number(t.amount||0); const merchant=(t.merchant_name||t.name||'Unknown merchant').trim(); return {id:txId(t,i),date:(t.date||t.posted_datetime||t.datetime||'').slice(0,10),name:t.name||merchant,merchant,account:t.account_name||t.account||'',amount,kind:amount<0?'income':'outflow',category:normalizeCategory(t.personal_finance_category_primary||t.category),confidence:t.personal_finance_category_confidence_level||'',channel:t.payment_channel||'',pending:!!t.pending,reviewed:false,owner:'Review',notes:'',raw:t};}
  function extractTransactions(pack){if(Array.isArray(pack)) return pack; if(Array.isArray(pack.transactions)) return pack.transactions; if(pack.data&&Array.isArray(pack.data.transactions)) return pack.data.transactions; if(pack.fullHistory&&Array.isArray(pack.fullHistory.transactions)) return pack.fullHistory.transactions; return [];}
  function importPack(pack,fileName='manual import'){const rows=extractTransactions(pack).map(normalizeTransaction); const map=new Map(GBV.state.transactions.map(t=>[t.id,t])); let added=0,updated=0; for(const tx of rows){if(map.has(tx.id)){map.set(tx.id,{...tx,...map.get(tx.id),raw:tx.raw}); updated++;}else{map.set(tx.id,tx); added++;}} GBV.state.transactions=[...map.values()].sort((a,b)=>(b.date||'').localeCompare(a.date||'')); GBV.state.source={fileName,importedAt:new Date().toISOString(),schema:pack.schema||'',version:pack.version||'',institution:pack.source?.institution||''}; GBV.state.meta.imports.unshift({fileName,at:GBV.state.source.importedAt,rows:rows.length,added,updated}); GBV.rules.applyAll(false); GBV.store.save(); return {rows:rows.length,added,updated,total:GBV.state.transactions.length};}
  function readFile(file){return new Promise((resolve,reject)=>{const r=new FileReader(); r.onload=()=>{try{resolve(JSON.parse(r.result));}catch(e){reject(e);}}; r.onerror=()=>reject(r.error); r.readAsText(file);});}
  function demo(){const today=new Date(); const d=n=>new Date(today.getTime()-n*86400000).toISOString().slice(0,10); return {schema:'gringotts.demo.v59',version:'demo',source:{institution:'Demo'},transactions:[{date:d(1),amount:-4518.55,name:'Coalfire Systems Payroll',merchant_name:'Coalfire Systems Payroll',personal_finance_category_primary:'income'},{date:d(2),amount:-4428.10,name:'VA Benefit Deposit',merchant_name:'VA Compensation and Pension',personal_finance_category_primary:'income'},{date:d(2),amount:1262,name:'Carrington Mortgage',merchant_name:'Carrington Mortgage Services',personal_finance_category_primary:'housing'},{date:d(3),amount:138.93,name:'Kroger',merchant_name:'Kroger',personal_finance_category_primary:'groceries'},{date:d(4),amount:82.40,name:'Spectrum',merchant_name:'Spectrum',personal_finance_category_primary:'bills_utilities'},{date:d(5),amount:70.40,name:'Highway 21 Seafood',merchant_name:'Highway 21 Seafood',personal_finance_category_primary:'dining_drinks'},{date:d(5),amount:93.01,name:'PetSmart',merchant_name:'PetSmart',personal_finance_category_primary:'pets'},{date:d(6),amount:1200,name:'Venmo',merchant_name:'Venmo',personal_finance_category_primary:'transfers'}]};}
  GBV.importer={money,normalizeCategory,importPack,readFile,demo};
})();
