(function(){
  const BUILD={version:'v96',name:'Calendar ICS + Executive Summary Roadmap'};
  const ROADMAP=[
    ['v97','Export Center','Export briefing, debt, promo, calendar prep, diagnostics, vault health, and ICS artifacts.'],
    ['v98','Executive Summary II','Restore the richer paragraph summary: current month, prior month, YTD, eating out, and biggest category increase/decrease.'],
    ['v99','Debug II','Deeper diagnostics and loaded-file proof.'],
    ['v100','PWA Rebuild Review','Only reintroduce install/offline after release gates.'],
    ['v101','Household Handoff','Spouse-device setup, restore checklist, and backup discipline.'],
    ['v102','Microservice Review','Evaluate optional API/service split after local-first runtime stabilizes.'],
    ['v103','Release Hardening','Formal smoke tests, rollback notes, and release acceptance gates.'],
    ['v104','Goals and Sinking Funds','Pool, truck, emergency fund, and large-purchase goals.'],
    ['v105','Budget Reports II','Cleaner family-facing category, merchant, and cash-flow reports.'],
    ['v106','Rules IV','Rule conflict review, undo support, and apply-history polish.']
  ];
  const RESTORED=[
    ['Calendar ICS','Generate a downloadable .ics file from bills, paydays, and promo APR dates.'],
    ['Executive Summary II queued','Current/prior/YTD/eating-out/category-movement summary is now explicitly on the roadmap.'],
    ['Rules III','Rule authoring, preview, apply, and delete remain active.'],
    ['Import Helper II','Safe JSON preview and helper summary remain active.']
  ];
  const QUEUED=[
    ['Executive Summary II','Richer paragraph summary requested by user.'],
    ['PWA install/offline','Paused until update reliability is proven.']
  ];
  function loadBase(){return new Promise((resolve,reject)=>{if(window.GringottsCleanRuntime?.BUILD?.version){resolve();return;}const s=document.createElement('script');s.src='src/runtime-v95.js?v=95';s.onload=resolve;s.onerror=()=>reject(new Error('Failed to load v95 base runtime'));document.body.appendChild(s);});}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k))||f;}catch(e){return f;}}
  function pad(n){return String(n).padStart(2,'0');}
  function compactDate(d){return String(d||'').replace(/-/g,'');}
  function validDate(d){return /^\d{4}-\d{2}-\d{2}$/.test(String(d||''));}
  function nextDateFromDay(day){const now=new Date();const y=now.getFullYear(),m=now.getMonth();const d=new Date(y,m,Math.max(1,Math.min(31,Number(day)||1)));if(d<new Date(now.getFullYear(),now.getMonth(),now.getDate()))d.setMonth(d.getMonth()+1);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
  function icsEscape(s){return String(s??'').replace(/\\/g,'\\\\').replace(/,/g,'\\,').replace(/;/g,'\\;').replace(/\n/g,'\\n');}
  function eventLine(e){const dt=compactDate(e.date);return ['BEGIN:VEVENT',`UID:${e.uid}@gringotts-budget-vault`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')}`,`DTSTART;VALUE=DATE:${dt}`,`SUMMARY:${icsEscape(e.title)}`,`DESCRIPTION:${icsEscape(e.description||'Generated by Gringotts Budget Vault v96.')}`,'END:VEVENT'].join('\r\n');}
  function calendarEvents(){const cf=readJSON('gringottsCashflowManual.v1',{bills:[],paydays:[]});const promo=readJSON('gringottsPromoAprWatch.v1',{cards:[]});const events=[];(cf.bills||[]).forEach((b,i)=>{const date=validDate(b.dueDate)?b.dueDate:(b.dueDay?nextDateFromDay(b.dueDay):'');if(date)events.push({uid:`bill-${b.id||i}-${date}`,date,title:`Bill due: ${b.name||'Bill'}`,description:`Amount: ${b.amount||0}`});});(cf.paydays||[]).forEach((p,i)=>{if(validDate(p.date))events.push({uid:`payday-${p.id||i}-${p.date}`,date:p.date,title:`Payday: ${p.name||'Payday'}`,description:`Amount: ${p.amount||0}`});});(promo.cards||[]).forEach((p,i)=>{if(validDate(p.promoEnd))events.push({uid:`promo-${p.id||i}-${p.promoEnd}`,date:p.promoEnd,title:`Promo APR ends: ${p.name||'Promo APR'}`,description:`Balance: ${p.balance||0}. Regular APR: ${p.regularApr||''}`});});return events.sort((a,b)=>a.date.localeCompare(b.date));}
  function buildICS(){const events=calendarEvents();return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Gringotts Budget Vault//v96//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH',...events.map(eventLine),'END:VCALENDAR'].join('\r\n');}
  function download(name,text,type='text/calendar'){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0);}
  async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Copied');}catch(e){download('Gringotts_calendar_export.ics',text);}}
  function toast(m){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t);}t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400);}
  function patchRuntime(){const rt=window.GringottsCleanRuntime;if(!rt)return false;if(rt.BUILD){rt.BUILD.version=BUILD.version;rt.BUILD.name=BUILD.name;}if(Array.isArray(rt.ROADMAP)){rt.ROADMAP.splice(0,rt.ROADMAP.length,...ROADMAP);}if(Array.isArray(rt.RESTORED)){rt.RESTORED.splice(0,rt.RESTORED.length,...RESTORED);}if(Array.isArray(rt.QUEUED)){rt.QUEUED.splice(0,rt.QUEUED.length,...QUEUED);}rt.calendarEvents=calendarEvents;rt.buildICS=buildICS;rt.downloadICS=()=>download('Gringotts_calendar_export_v96.ics',buildICS());return true;}
  function patchHeader(){document.title='Gringotts Budget Vault v96';const p=document.querySelector('.brand p');if(p)p.textContent='v96 Calendar ICS + Executive Summary Roadmap';}
  function injectICS(){const main=document.getElementById('main');if(!main||!main.textContent.includes('Tools'))return;if(document.getElementById('calendarIcsPanel'))return;const events=calendarEvents();const card=document.createElement('article');card.className='card';card.id='calendarIcsPanel';card.innerHTML=`<h3>Calendar ICS</h3><p>Generate a calendar import file from saved bills, paydays, and promo APR dates.</p><div class="summary-box">Events ready: ${events.length}\nBills/paydays/promos are exported as all-day calendar entries.\nExecutive Summary II is now queued on the roadmap.</div><div class="button-row"><button class="btn primary" id="downloadICS" type="button">Download ICS</button><button class="btn secondary" id="copyICS" type="button">Copy ICS text</button></div><div class="list">${events.slice(0,8).map(e=>`<div class="list-item"><span><strong>${esc(e.title)}</strong><br><small>${esc(e.date)}</small></span></div>`).join('')||'<p>No calendar-ready events yet. Add bills, paydays, or promo APR end dates in Planning.</p>'}</div>`;const inventory=[...main.querySelectorAll('.card')].find(x=>x.textContent.includes('Vault inventory'));if(inventory)main.insertBefore(card,inventory);else main.appendChild(card);const d=document.getElementById('downloadICS');if(d)d.onclick=()=>{download('Gringotts_calendar_export_v96.ics',buildICS());toast('ICS downloaded');};const c=document.getElementById('copyICS');if(c)c.onclick=()=>copyText(buildICS());}
  function patchDiagnostics(){const main=document.getElementById('main');if(!main||!main.textContent.includes('Diagnostics Center'))return;if(document.getElementById('v96DiagLine'))return;const box=main.querySelector('.summary-box');if(box){box.textContent=box.textContent.replace('Release: v95 Rules III','Release: v96 Calendar ICS + Executive Summary Roadmap')+`\nCalendar ICS events: ${calendarEvents().length}\nExecutive Summary II roadmap: queued`;box.id='v96DiagLine';}}
  function patchRoadmapNote(){const main=document.getElementById('main');if(!main||!main.textContent.includes('Roadmap'))return;if(document.getElementById('executiveSummaryRoadmapNote'))return;const card=document.createElement('article');card.className='card';card.id='executiveSummaryRoadmapNote';card.innerHTML='<h3>Executive Summary II request captured</h3><p>The richer paragraph summary is queued for v98: current month, last month, comparison, year to date, eating out, and biggest category increase/decrease.</p>';main.appendChild(card);}
  function patchAll(){patchRuntime();patchHeader();injectICS();patchDiagnostics();patchRoadmapNote();}
  loadBase().then(()=>{patchRuntime();setTimeout(()=>{window.GringottsCleanRuntime?.render?.();setTimeout(patchAll,150);},150);const obs=new MutationObserver(()=>patchAll());obs.observe(document.documentElement,{childList:true,subtree:true});}).catch(e=>{document.body.innerHTML='<main class="content"><article class="card"><h1>Gringotts v96 failed to load</h1><p>'+esc(e.message)+'</p></article></main>';});
})();
