(function(){
  const BUILD={version:'v92',name:'Navigation Cleanup + Restoration Roadmap',storageKey:'gringottsBudgetVault.latest'};
  const ROADMAP=[
    ['v93','Restore Editing Workflows','Add back editable cash-flow bills, payday markers, debt, promo APR, and meeting actions in the clean runtime.'],
    ['v94','Import Helper II','Restore pre-import analysis, coverage diff, duplicate review, and account mapping.'],
    ['v95','Rules III','Restore rule creation, rule preview, test matches, and safer bulk apply.'],
    ['v96','Calendar ICS','Generate ICS only after reviewing the calendar prep manifest.'],
    ['v97','Export Center','Export briefing, debt, promo, calendar prep, diagnostics, and vault health.'],
    ['v98','Debug II','Deeper diagnostics, copyable support bundle, and loaded-file proof.'],
    ['v99','PWA Rebuild Review','Only reintroduce install/offline after update path has release gates.'],
    ['v100','Household Handoff','Spouse-device setup, restore checklist, and backup discipline.'],
    ['v101','Microservice Review','Evaluate whether optional API/microservice support is worth it after local-first runtime stabilizes.'],
    ['v102','Release Hardening','Formal smoke tests, rollback notes, and release acceptance gates.']
  ];
  const LOST=[
    ['Editable cash-flow planning','Manual add/edit/remove bill and payday forms from v79.'],
    ['Debt planner entry forms','Manual debt and promo APR entry/edit forms from v78.'],
    ['Family meeting editing','Decision/action create, done/undo, copy/download meeting pack from v80.'],
    ['Import helper analysis','Safe JSON preview, warnings, duplicate estimate, top categories from v83.'],
    ['Calendar manifest builder','Build/copy/download calendar prep manifest from v84.'],
    ['Rule authoring','Rule create/test/apply workflows from earlier modular shell.'],
    ['PWA install/offline','Paused until update reliability is proven.']
  ];
  let active='dashboard',search='',selectedMonth=localStorage.getItem('gringottsCleanMonth.v1')||'';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
  const num=n=>Number(n||0);
  function toast(m){let t=$('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t);}t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400);}
  function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k))||f;}catch(e){return f;}}
  function vaults(){return Object.keys(localStorage).filter(k=>k.startsWith('gringottsBudgetVault.')&&k!=='gringottsBudgetVault.meta').map(key=>{try{const raw=localStorage.getItem(key)||'',obj=JSON.parse(raw);return {key,obj,bytes:raw.length,transactions:Array.isArray(obj.transactions)?obj.transactions.length:0,rules:Array.isArray(obj.rules)?obj.rules.length:0,last:Date.parse(obj.lastSavedAt||obj.createdAt||0)||0,version:obj.version||''};}catch(e){return {key,error:e.message,transactions:0,rules:0,bytes:0,last:0};}}).sort((a,b)=>b.transactions-a.transactions||b.last-a.last||a.key.localeCompare(b.key));}
  function bestVault(){return vaults()[0]||null;}
  function state(){const b=bestVault();return b&&b.obj?{...b.obj,transactions:Array.isArray(b.obj.transactions)?b.obj.transactions:[],rules:Array.isArray(b.obj.rules)?b.obj.rules:[],_activeKey:b.key}:{transactions:[],rules:[],_activeKey:'none'};}
  function txs(){return state().transactions||[];}
  function txDate(t){return String(t.date||t.authorized_date||t.datetime||'').slice(0,10);}
  function txName(t){return t.merchant||t.merchant_name||t.name||t.description||'Unknown';}
  function txCat(t){return t.category||t.personal_finance_category_primary||t.primaryCategory||'Other';}
  function txAcct(t){return t.account||t.accountName||t.account_name||t.official_name||t.account_id||'';}
  function monthOf(t){const d=txDate(t);return /^\d{4}-\d{2}/.test(d)?d.slice(0,7):'';}
  function months(){return [...new Set(txs().map(monthOf).filter(Boolean))].sort();}
  function ensureMonth(){const m=months();if(!selectedMonth||!m.includes(selectedMonth)){selectedMonth=m[m.length-1]||new Date().toISOString().slice(0,7);}localStorage.setItem('gringottsCleanMonth.v1',selectedMonth);return selectedMonth;}
  function addMonths(ym,n){const [y,m]=ym.split('-').map(Number),d=new Date(y,m-1+n,1);return d.toISOString().slice(0,7);}
  function monthLabel(ym){const [y,m]=ym.split('-'),d=new Date(Number(y),Number(m)-1,1);return d.toLocaleString(undefined,{month:'short',year:'2-digit'}).toUpperCase();}
  function metricsFor(ym){let income=0,spend=0,count=0;const cats=new Map(),merchants=new Map();txs().forEach(t=>{if(monthOf(t)!==ym)return;count++;const a=num(t.amount);if(a<0)income+=Math.abs(a);else spend+=Math.abs(a);const c=txCat(t);cats.set(c,(cats.get(c)||0)+(a>0?Math.abs(a):0));const n=txName(t);merchants.set(n,(merchants.get(n)||0)+(a>0?Math.abs(a):0));});return {ym,income,spend,net:income-spend,count,cats,merchants};}
  function ytd(ym){const y=ym.slice(0,4);let income=0,spend=0,count=0;txs().forEach(t=>{if(monthOf(t).slice(0,4)!==y)return;count++;const a=num(t.amount);if(a<0)income+=Math.abs(a);else spend+=Math.abs(a);});return {income,spend,net:income-spend,count};}
  function topMap(map,n=5){return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,n);}
  function download(name,text,type='application/json'){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0);}
  function backup(){const b=bestVault();if(!b){toast('No vault found');return;}download(`Gringotts_v92_backup_${b.transactions}_transactions_${new Date().toISOString().replace(/[:.]/g,'-')}.json`,JSON.stringify(b.obj,null,2));toast('Backup downloaded');}
  async function swStatus(){let registrations=[],cacheNames=[];try{if('serviceWorker'in navigator){registrations=await navigator.serviceWorker.getRegistrations();for(const r of registrations){try{await r.unregister();}catch(e){}}registrations=await navigator.serviceWorker.getRegistrations();}}catch(e){}try{if(window.caches&&window.caches.keys)cacheNames=(await window.caches.keys()).filter(k=>k.toLowerCase().includes('gringotts'));}catch(e){cacheNames=['cache status error: '+(e.message||e)];}return {serviceWorkers:registrations.length,controller:!!navigator.serviceWorker?.controller,caches:cacheNames};}
  async function debugReport(){const st=await swStatus(),b=bestVault();return {runtimeVersion:BUILD.version,buildName:BUILD.name,time:new Date().toISOString(),url:location.href,title:document.title,userAgent:navigator.userAgent,storage:{activeKey:b?.key||'none',activeTransactions:txs().length,bestVault:b?{key:b.key,transactions:b.transactions,rules:b.rules,bytes:b.bytes,version:b.version}:null,vaults:vaults().map(v=>({key:v.key,transactions:v.transactions,rules:v.rules,bytes:v.bytes,version:v.version,last:v.last}))},serviceWorker:st,localStorageKeys:Object.keys(localStorage).filter(k=>k.startsWith('gringotts')).sort(),loadedRuntime:'src/runtime-v92.js'};}
  async function copyDebug(){const text=JSON.stringify(await debugReport(),null,2);try{await navigator.clipboard.writeText(text);toast('Debug report copied');}catch(e){download('Gringotts_debug_v92.json',text);toast('Debug report downloaded');}}
  function shell(){document.body.innerHTML=`<a class="skip-link" href="#main">Skip to main content</a><div class="app-shell"><header class="topbar"><div class="brand"><div class="crest" aria-hidden="true">₲</div><div><h1>Gringotts Budget Vault</h1><p>${BUILD.version} ${BUILD.name}</p></div></div><div class="topbar-actions"><button class="btn secondary" id="backupBtn" type="button">Download backup</button><button class="btn secondary" id="debugBtn" type="button">Copy debug</button></div></header><nav class="tabs" id="tabs"></nav><main id="main" class="content"></main></div><div id="toast" class="toast" role="status"></div>`;$('backupBtn').onclick=backup;$('debugBtn').onclick=copyDebug;}
  function section(name){active=name;render();setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),0);}
  function tabs(){const list=[['dashboard','Dashboard'],['ledger','Ledger'],['planning','Planning'],['tools','Tools'],['diagnostics','Diagnostics'],['roadmap','Roadmap']];$('tabs').innerHTML=list.map(t=>`<button class="tab ${active===t[0]?'active':''}" data-sec="${t[0]}" type="button">${t[1]}</button>`).join('');document.querySelectorAll('[data-sec]').forEach(b=>b.onclick=()=>section(b.dataset.sec));}
  function dashboard(){const ym=ensureMonth(),cur=metricsFor(ym),prev=metricsFor(addMonths(ym,-1)),year=ytd(ym),change=cur.spend-prev.spend;return `<section class="section active"><div class="section-title-row"><div><h2>Vault Dashboard</h2><p>Clean runtime with grouped mobile navigation.</p></div><span class="pill">${txs().length} transactions</span></div><article class="card"><h3>Executive summary</h3><div class="month-picker"><button class="btn secondary" id="monthPrev" type="button">‹</button><button class="btn secondary" id="monthPick" type="button">${monthLabel(ym)}</button><button class="btn secondary" id="monthNext" type="button">›</button></div><p>For ${monthLabel(ym)}, income is ${money(cur.income)} and spending is ${money(cur.spend)}, leaving net cash flow of ${money(cur.net)}. Compared with ${monthLabel(prev.ym)}, spending is ${change>=0?'up':'down'} ${money(Math.abs(change))}. Year to date, income is ${money(year.income)}, spending is ${money(year.spend)}, and net cash flow is ${money(year.net)}.</p></article><div class="grid four"><article class="card"><h3>Income</h3><div class="big-number">${money(cur.income)}</div></article><article class="card"><h3>Spending</h3><div class="big-number">${money(cur.spend)}</div></article><article class="card"><h3>Net</h3><div class="big-number">${money(cur.net)}</div></article><article class="card"><h3>Rows</h3><div class="big-number">${cur.count}</div></article></div><div class="grid two"><article class="card"><h3>Top categories</h3><div class="list">${topMap(cur.cats).map(x=>`<div class="list-item"><span>${esc(x[0])}</span><span class="pill">${money(x[1])}</span></div>`).join('')||'<p>No category data.</p>'}</div></article><article class="card"><h3>Mobile tools hub</h3><div class="button-row"><button class="btn secondary" data-jump="planning" type="button">Planning</button><button class="btn secondary" data-jump="tools" type="button">Tools</button><button class="btn secondary" data-jump="diagnostics" type="button">Diagnostics</button><button class="btn secondary" data-jump="roadmap" type="button">Roadmap</button></div></article></div></section>`;}
  function ledger(){const q=search.toLowerCase().trim(),rows=txs().filter(t=>!q||[txDate(t),txName(t),txCat(t),txAcct(t),String(t.amount)].join(' ').toLowerCase().includes(q)).slice(0,500);return `<section class="section active"><h2>Ledger</h2><input id="ledgerSearch" class="input" placeholder="Search date, merchant, category, account" value="${esc(search)}"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Merchant</th><th>Category</th><th>Amount</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${esc(txDate(t))}</td><td>${esc(txName(t))}<br><small>${esc(txAcct(t))}</small></td><td>${esc(txCat(t))}</td><td>${money(t.amount)}</td></tr>`).join('')}</tbody></table></div></section>`;}
  function planning(){const manual=readJSON('gringottsCashflowManual.v1',{bills:[],paydays:[]}),debts=readJSON('gringottsDebtPlanner.v1',{debts:[],extraPayment:0}),promo=readJSON('gringottsPromoAprWatch.v1',{cards:[]}),meeting=readJSON('gringottsFamilyMeetingPack.v1',{decisions:[],actions:[]});const debtTotal=(debts.debts||[]).reduce((a,x)=>a+num(x.balance),0),promoTotal=(promo.cards||[]).reduce((a,x)=>a+num(x.balance),0);return `<section class="section active"><h2>Planning</h2><p>Read-only clean-runtime summaries. Editing workflows are explicitly queued on the roadmap.</p><div class="grid two"><article class="card"><h3>Cash Flow</h3><p>${(manual.bills||[]).length} bills • ${(manual.paydays||[]).length} paydays</p><div class="list">${(manual.bills||[]).slice(0,5).map(b=>`<div class="list-item"><span>${esc(b.name||'Bill')}</span><span class="pill">${money(b.amount)}</span></div>`).join('')||'<p>No manual bills saved yet.</p>'}</div></article><article class="card"><h3>Debt / Promo</h3><p>Debt: ${money(debtTotal)} • Promo: ${money(promoTotal)}</p><div class="list">${(promo.cards||[]).slice(0,5).map(x=>`<div class="list-item"><span>${esc(x.name||'Promo')}<br><small>Ends ${esc(x.promoEnd||'date needed')}</small></span><span class="pill">${money(x.balance)}</span></div>`).join('')||'<p>No promo APR balances saved yet.</p>'}</div></article><article class="card"><h3>Briefing / Family Meeting</h3><p>${(meeting.decisions||[]).length} decisions • ${(meeting.actions||[]).length} actions</p><div class="list">${(meeting.actions||[]).slice(0,5).map(x=>`<div class="list-item"><span>${x.done?'✓ ':''}${esc(x.owner||'Household')}: ${esc(x.text)}</span></div>`).join('')||'<p>No meeting actions saved yet.</p>'}</div></article><article class="card"><h3>Restore queue</h3><div class="list">${LOST.slice(0,4).map(x=>`<div class="list-item"><span><strong>${esc(x[0])}</strong><br><small>${esc(x[1])}</small></span><span class="pill">queued</span></div>`).join('')}</div></article></div></section>`;}
  function tools(){const rules=state().rules||[],cal=readJSON('gringottsCalendarPrep.v1',null),helper=readJSON('gringottsImportHelper.v1',null);return `<section class="section active"><h2>Tools</h2><div class="grid two"><article class="card"><h3>Safety</h3><p>Best vault: ${esc(bestVault()?.key||'none')} • ${bestVault()?.transactions||0} transactions.</p><button class="btn primary" id="safetyBackup" type="button">Download best vault backup</button></article><article class="card"><h3>Import / Restore</h3><p>Restore JSON backup to <code>gringottsBudgetVault.latest</code>.</p><input id="restoreFile" type="file" accept=".json,application/json"><button class="btn primary" id="restoreBtn" type="button">Restore selected backup</button></article><article class="card"><h3>Rules</h3><p>${rules.length} rules found.</p><p>Rule editing is queued for v95.</p></article><article class="card"><h3>Import Helper / Calendar Prep</h3><p>Last helper: ${helper?.summary?helper.summary.rowCount+' rows':'none'}.</p><p>Calendar manifest: ${cal?.manifest?cal.manifest.totalEvents+' events':'none'}.</p></article></div><article class="card"><h3>Vault inventory</h3><div class="list">${vaults().map(v=>`<div class="list-item"><span><strong>${esc(v.key)}</strong><br><small>${v.transactions} transactions • ${(v.bytes/1024).toFixed(0)} KB • ${esc(v.version)}</small></span></div>`).join('')}</div></article></section>`;}
  async function diagnostics(){const st=await swStatus(),b=bestVault(),activeCount=txs().length,tests=[['Runtime version',BUILD.version==='v92',BUILD.version],['No service worker',st.serviceWorkers===0,`${st.serviceWorkers} registrations`],['No controller',!st.controller,st.controller?'controller active':'none'],['No Gringotts caches',st.caches.length===0,st.caches.join(', ')||'none'],['Best vault',!!(b&&b.transactions>0),b?`${b.transactions} transactions in ${b.key}`:'none'],['Active vault loaded',!!(b&&activeCount===b.transactions),`${activeCount} active / ${b?.transactions??'unknown'} best`],['Grouped nav',true,'6 primary tabs'],['Roadmap count',ROADMAP.length===10,`${ROADMAP.length} releases`],['Restore queue',LOST.length>=7,`${LOST.length} lost-functionality items tracked`]];return `<section class="section active"><h2>Diagnostics Center</h2><article class="card"><h3>Runtime summary</h3><div class="summary-box">Release: ${BUILD.version} ${BUILD.name}\nActive storage key: ${b?.key||'none'}\nActive transactions: ${activeCount}\nBest local vault transactions: ${b?.transactions??0}\nService workers: ${st.serviceWorkers}\nController active: ${st.controller?'yes':'no'}\nCached Gringotts shells: ${st.caches.join(', ')||'none visible'}\nRoadmap count: ${ROADMAP.length}\nLost-functionality queue: ${LOST.length}</div><div class="button-row"><button class="btn secondary" id="copyDebug2" type="button">Copy debug report</button><button class="btn secondary" id="downloadBackup2" type="button">Download backup</button></div></article><article class="card"><h3>Runtime self tests</h3><div class="list">${tests.map(r=>`<div class="list-item"><span><strong>${esc(r[0])}</strong><br><small>${esc(r[2])}</small></span><span class="pill">${r[1]?'PASS':'WARN'}</span></div>`).join('')}</div></article></section>`;}
  function roadmap(){return `<section class="section active"><h2>Roadmap</h2><p>Exactly the next 10 planned releases, now including the lost-functionality restore queue.</p><div class="roadmap">${ROADMAP.map(r=>`<div class="roadmap-item"><span class="pill">${esc(r[0])}</span><h3>${esc(r[1])}</h3><p>${esc(r[2])}</p></div>`).join('')}</div><article class="card"><h3>Lost functionality tracker</h3><div class="list">${LOST.map(x=>`<div class="list-item"><span><strong>${esc(x[0])}</strong><br><small>${esc(x[1])}</small></span><span class="pill">tracked</span></div>`).join('')}</div></article></section>`;}
  async function render(){tabs();let html='';if(active==='dashboard')html=dashboard();else if(active==='ledger')html=ledger();else if(active==='planning')html=planning();else if(active==='tools')html=tools();else if(active==='diagnostics')html=await diagnostics();else if(active==='roadmap')html=roadmap();$('main').innerHTML=html;bind();}
  function bind(){document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>section(b.dataset.jump));const p=$('monthPrev');if(p)p.onclick=()=>{selectedMonth=addMonths(ensureMonth(),-1);localStorage.setItem('gringottsCleanMonth.v1',selectedMonth);render();};const n=$('monthNext');if(n)n.onclick=()=>{selectedMonth=addMonths(ensureMonth(),1);localStorage.setItem('gringottsCleanMonth.v1',selectedMonth);render();};const s=$('ledgerSearch');if(s)s.oninput=e=>{search=e.target.value;render();};const c=$('copyDebug2');if(c)c.onclick=copyDebug;const b=$('downloadBackup2');if(b)b.onclick=backup;const sb=$('safetyBackup');if(sb)sb.onclick=backup;const rb=$('restoreBtn');if(rb)rb.onclick=restoreBackup;}
  function restoreBackup(){const f=$('restoreFile')?.files?.[0];if(!f){toast('Select a JSON backup first');return;}const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result);if(!Array.isArray(obj.transactions))throw new Error('Backup has no transactions array');localStorage.setItem(BUILD.storageKey,JSON.stringify({...obj,version:BUILD.version,lastSavedAt:new Date().toISOString()}));toast('Backup restored to latest');render();}catch(e){toast('Restore failed: '+e.message);}};r.readAsText(f);}
  async function boot(){try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs){try{await r.unregister();}catch(e){}}}}catch(e){}shell();await render();}
  document.addEventListener('DOMContentLoaded',boot);
  window.GringottsCleanRuntime={BUILD,ROADMAP,LOST,vaults,bestVault,state,debugReport,copyDebug,backup,render};
})();
