(function(){
  const BUILD={version:'v90',name:'Clean Runtime Shell',storageKey:'gringottsBudgetVault.latest'};
  const ROADMAP=[['v91','Cash Flow III','Recurring bill confirm/edit workflow and payday templates.'],['v92','Navigation Cleanup','Mobile tab cleanup after clean runtime stabilizes.'],['v93','Calendar ICS','Generate ICS after calendar prep manifest review.'],['v94','Import Helper II','Coverage diff, duplicate review, and account mapping.'],['v95','Update Proof','Show loaded file versions and deployment proof clearly.'],['v96','Rules III','Rule preview, test matches, and safer bulk apply.'],['v97','Debug II','Deeper diagnostics and shareable support bundle.'],['v98','PWA Rebuild','Reintroduce install/offline only after update path is proven.'],['v99','Household Handoff','Spouse-device setup, restore, and backup checklist.'],['v100','Release Hardening','Formal smoke tests, rollback notes, and release gates.']];
  let activeSection='dashboard';
  let search='';
  let selectedMonth=localStorage.getItem('gringottsCleanMonth.v1')||'';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
  const num=n=>Number(n||0);
  function toast(m){let t=$('toast'); if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t);} t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400);}
  function vaults(){return Object.keys(localStorage).filter(k=>k.startsWith('gringottsBudgetVault.')&&k!=='gringottsBudgetVault.meta').map(key=>{try{const raw=localStorage.getItem(key)||'';const obj=JSON.parse(raw);return {key,obj,bytes:raw.length,transactions:Array.isArray(obj.transactions)?obj.transactions.length:0,rules:Array.isArray(obj.rules)?obj.rules.length:0,last:Date.parse(obj.lastSavedAt||obj.createdAt||0)||0,version:obj.version||''};}catch(e){return {key,error:e.message,transactions:0,rules:0,bytes:0,last:0};}}).sort((a,b)=>b.transactions-a.transactions||b.last-a.last||a.key.localeCompare(b.key));}
  function bestVault(){return vaults()[0]||null;}
  function state(){const b=bestVault();return b&&b.obj?{...b.obj,transactions:Array.isArray(b.obj.transactions)?b.obj.transactions:[],rules:Array.isArray(b.obj.rules)?b.obj.rules:[],_activeKey:b.key}: {transactions:[],rules:[],_activeKey:'none'};}
  function txs(){return state().transactions||[];}
  function txDate(t){return String(t.date||t.authorized_date||t.datetime||'').slice(0,10);}
  function txName(t){return t.merchant||t.merchant_name||t.name||t.description||'Unknown';}
  function txCat(t){return t.category||t.personal_finance_category_primary||t.primaryCategory||'Other';}
  function txAcct(t){return t.account||t.accountName||t.account_name||t.official_name||t.account_id||'';}
  function monthOf(t){const d=txDate(t);return /^\d{4}-\d{2}/.test(d)?d.slice(0,7):'';}
  function months(){const m=[...new Set(txs().map(monthOf).filter(Boolean))].sort();return m;}
  function ensureMonth(){const m=months(); if(!selectedMonth||!m.includes(selectedMonth)){selectedMonth=m[m.length-1]||new Date().toISOString().slice(0,7);} localStorage.setItem('gringottsCleanMonth.v1',selectedMonth);return selectedMonth;}
  function addMonths(ym,n){const [y,m]=ym.split('-').map(Number);const d=new Date(y,m-1+n,1);return d.toISOString().slice(0,7);}
  function monthLabel(ym){const [y,m]=ym.split('-');const d=new Date(Number(y),Number(m)-1,1);return d.toLocaleString(undefined,{month:'short',year:'2-digit'}).toUpperCase();}
  function metricsFor(ym){let income=0,spend=0,count=0; const cats=new Map(); const merchants=new Map(); txs().forEach(t=>{if(monthOf(t)!==ym)return;count++;const a=num(t.amount);if(a<0)income+=Math.abs(a);else spend+=Math.abs(a);const c=txCat(t);cats.set(c,(cats.get(c)||0)+(a>0?Math.abs(a):0));const n=txName(t);merchants.set(n,(merchants.get(n)||0)+(a>0?Math.abs(a):0));});return {ym,income,spend,net:income-spend,count,cats,merchants};}
  function ytd(ym){const y=ym.slice(0,4);let income=0,spend=0,count=0;txs().forEach(t=>{if(monthOf(t).slice(0,4)!==y)return;count++;const a=num(t.amount);if(a<0)income+=Math.abs(a);else spend+=Math.abs(a);});return {income,spend,net:income-spend,count};}
  function topMap(map,n=5){return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,n);}
  function download(name,text,type='application/json'){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0);}
  function backup(){const b=bestVault();if(!b){toast('No vault found');return;}download(`Gringotts_v90_backup_${b.transactions}_transactions_${new Date().toISOString().replace(/[:.]/g,'-')}.json`,JSON.stringify(b.obj,null,2));toast('Backup downloaded');}
  function section(name){activeSection=name;render();window.scrollTo({top:0,behavior:'smooth'});}
  async function swStatus(){let regs=[],caches=[];try{if('serviceWorker'in navigator){regs=await navigator.serviceWorker.getRegistrations();for(const r of regs){try{await r.unregister();}catch(e){}}regs=await navigator.serviceWorker.getRegistrations();}}catch(e){}try{if('caches'in window)caches=(await caches.keys()).filter(k=>k.toLowerCase().includes('gringotts'));}catch(e){}return {serviceWorkers:regs.length,controller:!!navigator.serviceWorker?.controller,caches};}
  async function debugReport(){const st=await swStatus();const b=bestVault();return {runtimeVersion:BUILD.version,buildName:BUILD.name,time:new Date().toISOString(),url:location.href,title:document.title,userAgent:navigator.userAgent,viewport:{w:innerWidth,h:innerHeight,dpr:devicePixelRatio},storage:{activeKey:b?.key||'none',activeTransactions:(state().transactions||[]).length,bestVault:b?{key:b.key,transactions:b.transactions,rules:b.rules,bytes:b.bytes,version:b.version}:null,vaults:vaults().map(v=>({key:v.key,transactions:v.transactions,rules:v.rules,bytes:v.bytes,version:v.version,last:v.last}))},serviceWorker:st,localStorageKeys:Object.keys(localStorage).filter(k=>k.startsWith('gringotts')).sort(),scripts:[...document.scripts].map(s=>s.src||'[inline]').filter(Boolean)};}
  async function copyDebug(){const text=JSON.stringify(await debugReport(),null,2);try{await navigator.clipboard.writeText(text);}catch(e){download('Gringotts_debug_v90.json',text);}toast('Debug report copied');}
  function renderAppShell(){document.body.innerHTML=`<a class="skip-link" href="#main">Skip to main content</a><div class="app-shell"><header class="topbar"><div class="brand"><div class="crest" aria-hidden="true">₲</div><div><h1>Gringotts Budget Vault</h1><p>${BUILD.version} ${BUILD.name}</p></div></div><div class="topbar-actions"><button class="btn secondary" id="backupBtn" type="button">Download backup</button><button class="btn secondary" id="debugBtn" type="button">Copy debug</button></div></header><nav class="tabs" id="tabs"></nav><main id="main" class="content"></main></div><div id="toast" class="toast" role="status"></div>`; $('backupBtn').onclick=backup;$('debugBtn').onclick=copyDebug;}
  function renderTabs(){const tabs=[['dashboard','Dashboard'],['ledger','Ledger'],['cashflow','Cash Flow'],['import','Import'],['health','Diagnostics'],['roadmap','Roadmap']];$('tabs').innerHTML=tabs.map(t=>`<button class="tab ${activeSection===t[0]?'active':''}" data-sec="${t[0]}" type="button">${t[1]}</button>`).join('');document.querySelectorAll('[data-sec]').forEach(b=>b.onclick=()=>section(b.dataset.sec));}
  function dashboard(){const ym=ensureMonth();const cur=metricsFor(ym);const prev=metricsFor(addMonths(ym,-1));const year=ytd(ym);const change=cur.spend-prev.spend;return `<section class="section active"><div class="section-title-row"><div><h2>Vault Dashboard</h2><p>Clean runtime; no legacy release bridge, no service worker, local vault only.</p></div><span class="pill">${txs().length} transactions</span></div><article class="card"><h3>Executive summary</h3><div class="month-picker"><button class="btn secondary" id="monthPrev" type="button">‹</button><button class="btn secondary" id="monthPick" type="button">${monthLabel(ym)}</button><button class="btn secondary" id="monthNext" type="button">›</button></div><p id="execText">For ${monthLabel(ym)}, income is ${money(cur.income)} and spending is ${money(cur.spend)}, leaving net cash flow of ${money(cur.net)}. Compared with ${monthLabel(prev.ym)}, spending is ${change>=0?'up':'down'} ${money(Math.abs(change))}. Year to date, income is ${money(year.income)}, spending is ${money(year.spend)}, and net cash flow is ${money(year.net)}.</p></article><div class="grid four"><article class="card"><h3>Income</h3><div class="big-number">${money(cur.income)}</div></article><article class="card"><h3>Spending</h3><div class="big-number">${money(cur.spend)}</div></article><article class="card"><h3>Net</h3><div class="big-number">${money(cur.net)}</div></article><article class="card"><h3>Rows</h3><div class="big-number">${cur.count}</div></article></div><div class="grid two"><article class="card"><h3>Top categories</h3><div class="list">${topMap(cur.cats).map(x=>`<div class="list-item"><span>${esc(x[0])}</span><span class="pill">${money(x[1])}</span></div>`).join('')||'<p>No category data.</p>'}</div></article><article class="card"><h3>Top merchants</h3><div class="list">${topMap(cur.merchants).map(x=>`<div class="list-item"><span>${esc(x[0])}</span><span class="pill">${money(x[1])}</span></div>`).join('')||'<p>No merchant data.</p>'}</div></article></div></section>`;}
  function ledger(){const q=search.toLowerCase().trim();const rows=txs().filter(t=>!q||[txDate(t),txName(t),txCat(t),txAcct(t),String(t.amount)].join(' ').toLowerCase().includes(q)).slice(0,500);return `<section class="section active"><h2>Ledger</h2><p>Searches the active local vault. Showing up to 500 rows.</p><input id="ledgerSearch" class="input" placeholder="Search date, merchant, category, account" value="${esc(search)}"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Merchant</th><th>Category</th><th>Amount</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${esc(txDate(t))}</td><td>${esc(txName(t))}<br><small>${esc(txAcct(t))}</small></td><td>${esc(txCat(t))}</td><td>${money(t.amount)}</td></tr>`).join('')}</tbody></table></div></section>`;}
  function cashflow(){const manual=JSON.parse(localStorage.getItem('gringottsCashflowManual.v1')||'{"bills":[],"paydays":[]}');const cal=JSON.parse(localStorage.getItem('gringottsCalendarPrep.v1')||'null');return `<section class="section active"><h2>Cash Flow</h2><div class="grid two"><article class="card"><h3>Manual bills</h3><div class="list">${(manual.bills||[]).map(b=>`<div class="list-item"><span>${esc(b.name||'Bill')}<br><small>Due day ${esc(b.dueDay||'')}</small></span><span class="pill">${money(b.amount)}</span></div>`).join('')||'<p>No manual bills saved yet.</p>'}</div></article><article class="card"><h3>Payday markers</h3><div class="list">${(manual.paydays||[]).map(p=>`<div class="list-item"><span>${esc(p.name||'Payday')}<br><small>${esc(p.date||'')}</small></span><span class="pill">${money(p.amount)}</span></div>`).join('')||'<p>No payday markers saved yet.</p>'}</div></article></div><article class="card"><h3>Calendar prep</h3><p>${cal?.manifest?`${cal.manifest.totalEvents} events in latest manifest.`:'No calendar prep manifest saved yet.'}</p></article></section>`;}
  function importSection(){return `<section class="section active"><h2>Import / Restore</h2><article class="card"><h3>Restore JSON backup to latest</h3><p>This writes only to <code>gringottsBudgetVault.latest</code>. Download a backup first.</p><input id="restoreFile" type="file" accept=".json,application/json"><button class="btn primary" id="restoreBtn" type="button">Restore selected backup</button></article><article class="card"><h3>Vault inventory</h3><div class="list">${vaults().map(v=>`<div class="list-item"><span><strong>${esc(v.key)}</strong><br><small>${v.transactions} transactions • ${(v.bytes/1024).toFixed(0)} KB • ${esc(v.version)}</small></span></div>`).join('')}</div></article></section>`;}
  async function health(){const st=await swStatus();const b=bestVault();const active=txs().length;const tests=[['Runtime version',BUILD.version==='v90',BUILD.version],['No service worker',st.serviceWorkers===0,`${st.serviceWorkers} registrations`],['No controller',!st.controller,st.controller?'controller active':'none'],['No Gringotts caches',st.caches.length===0,st.caches.join(', ')||'none'],['Best vault',!!(b&&b.transactions>0),b?`${b.transactions} transactions in ${b.key}`:'none'],['Active vault loaded',!!(b&&active===b.transactions),`${active} active / ${b?.transactions??'unknown'} best`],['Roadmap count',ROADMAP.length===10,`${ROADMAP.length} releases`]];return `<section class="section active"><h2>Diagnostics Center</h2><article class="card"><h3>Runtime summary</h3><div class="summary-box">Release: ${BUILD.version} ${BUILD.name}\nActive storage key: ${b?.key||'none'}\nActive transactions: ${active}\nBest local vault transactions: ${b?.transactions??0}\nService workers: ${st.serviceWorkers}\nController active: ${st.controller?'yes':'no'}\nCached Gringotts shells: ${st.caches.join(', ')||'none visible'}\nRoadmap count: ${ROADMAP.length}</div><div class="button-row"><button class="btn secondary" id="copyDebug2" type="button">Copy debug report</button><button class="btn secondary" id="downloadBackup2" type="button">Download backup</button></div></article><article class="card"><h3>Runtime self tests</h3><div class="list">${tests.map(r=>`<div class="list-item"><span><strong>${esc(r[0])}</strong><br><small>${esc(r[2])}</small></span><span class="pill">${r[1]?'PASS':'WARN'}</span></div>`).join('')}</div></article></section>`;}
  function roadmap(){return `<section class="section active"><h2>Roadmap</h2><p>Exactly the next 10 planned releases from this clean runtime.</p><div class="roadmap">${ROADMAP.map(r=>`<div class="roadmap-item"><span class="pill">${esc(r[0])}</span><h3>${esc(r[1])}</h3><p>${esc(r[2])}</p></div>`).join('')}</div></section>`;}
  async function render(){renderTabs();let html='';if(activeSection==='dashboard')html=dashboard();if(activeSection==='ledger')html=ledger();if(activeSection==='cashflow')html=cashflow();if(activeSection==='import')html=importSection();if(activeSection==='health')html=await health();if(activeSection==='roadmap')html=roadmap();$('main').innerHTML=html;bindSection();}
  function bindSection(){const p=$('monthPrev');if(p)p.onclick=()=>{selectedMonth=addMonths(ensureMonth(),-1);localStorage.setItem('gringottsCleanMonth.v1',selectedMonth);render();};const n=$('monthNext');if(n)n.onclick=()=>{selectedMonth=addMonths(ensureMonth(),1);localStorage.setItem('gringottsCleanMonth.v1',selectedMonth);render();};const ms=$('ledgerSearch');if(ms)ms.oninput=e=>{search=e.target.value;render();};const c=$('copyDebug2');if(c)c.onclick=copyDebug;const db=$('downloadBackup2');if(db)db.onclick=backup;const rb=$('restoreBtn');if(rb)rb.onclick=restoreBackup;}
  function restoreBackup(){const f=$('restoreFile')?.files?.[0];if(!f){toast('Select a JSON backup first');return;}const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result);if(!Array.isArray(obj.transactions))throw new Error('Backup has no transactions array');localStorage.setItem(BUILD.storageKey,JSON.stringify({...obj,version:BUILD.version,lastSavedAt:new Date().toISOString()}));toast('Backup restored to latest');render();}catch(e){toast('Restore failed: '+e.message);}};r.readAsText(f);}
  async function boot(){try{if('serviceWorker'in navigator){const regs=await navigator.serviceWorker.getRegistrations();for(const r of regs){try{await r.unregister();}catch(e){}}}}catch(e){}renderAppShell();await render();}
  document.addEventListener('DOMContentLoaded',boot);
  window.GringottsCleanRuntime={BUILD,ROADMAP,vaults,bestVault,state,debugReport,copyDebug,backup,render};
})();