(function(){
  const GBV=window.GBV;
  const $=sel=>document.querySelector(sel);
  function escape(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
  function money(n){return GBV.importer.money(n);}
  function setSection(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.section===name)); document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===`section-${name}`)); if(name==='review') renderReview(); if(name==='transactions') renderLedger();}
  function renderDashboard(){const m=GBV.reports.metrics(); $('#dataStatus').textContent=m.all.length?`${m.all.length} transactions • ${GBV.state.source?.institution||'local data'}`:'No data imported'; $('#kpiGrid').innerHTML=[['Recent income',money(m.income)],['Recent outflow',money(m.outflow)],['Recent net',money(m.net)],['Needs review',m.unreviewed]].map(([l,v])=>`<div class="kpi"><strong>${escape(v)}</strong><span>${escape(l)}</span></div>`).join(''); const max=m.category[0]?.[1]||1; $('#categoryBars').innerHTML=m.category.slice(0,8).map(([k,v])=>`<div class="bar-row"><div class="bar-label">${escape(k)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,v/max*100)}%"></div></div><div>${money(v)}</div></div>`).join('')||'<p>No spending categories yet.</p>'; $('#merchantList').innerHTML=m.merchant.slice(0,8).map(([k,v])=>`<div class="list-item"><span>${escape(k)}</span><strong>${money(v)}</strong></div>`).join('')||'<p>No merchants yet.</p>'; $('#advisorNotes').innerHTML=GBV.reports.notes(m).map(n=>`<div class="note">${escape(n)}</div>`).join(''); $('#reviewProgress').textContent=`${m.reviewed} reviewed • ${m.unreviewed} left`;}
  function nextUnreviewed(){const txs=GBV.state.transactions; if(!txs.length) return null; return txs.find(t=>!t.reviewed)||txs[0];}
  function renderReview(){const tx=nextUnreviewed(); if(!tx){$('#reviewCard').innerHTML='<h3>No transactions imported yet</h3><p>Import a JSON pack to start review.</p>'; return;} const income=tx.amount<0; $('#reviewCard').innerHTML=`<h3>${escape(tx.merchant)}</h3><div class="review-amount ${income?'income':'outflow'}">${income?'+':'−'}${money(Math.abs(tx.amount))}</div><div class="review-meta"><span>${escape(tx.date)} • ${escape(tx.account||'No account')}</span><span>${escape(tx.name)}</span><span>Current: ${escape(tx.category)} / ${escape(tx.owner)}</span></div><div class="review-form"><label>Category<select id="reviewCategory">${GBV.CATEGORIES.map(c=>`<option ${c===tx.category?'selected':''}>${escape(c)}</option>`).join('')}</select></label><label>Owner<select id="reviewOwner">${GBV.OWNERS.map(o=>`<option ${o===tx.owner?'selected':''}>${escape(o)}</option>`).join('')}</select></label><label style="grid-column:1/-1">Notes<textarea id="reviewNotes" rows="3">${escape(tx.notes||'')}</textarea></label></div><div class="button-row" style="margin-top:1rem"><button class="btn primary" id="markReviewedBtn" type="button">Mark reviewed</button><button class="btn secondary" id="makeRuleBtn" type="button">Create rule from merchant</button><button class="btn secondary" id="skipReviewBtn" type="button">Skip</button></div>`; $('#markReviewedBtn').onclick=()=>{tx.category=$('#reviewCategory').value; tx.owner=$('#reviewOwner').value; tx.notes=$('#reviewNotes').value; tx.reviewed=true; GBV.store.save(false); renderAll(); renderReview(); GBV.store.toast('Transaction reviewed');}; $('#makeRuleBtn').onclick=()=>{try{GBV.rules.add(tx.merchant,$('#reviewCategory').value,$('#reviewOwner').value); tx.reviewed=true; GBV.store.save(false); renderAll(); renderReview(); GBV.store.toast('Rule created and applied');}catch(e){GBV.store.toast(e.message);}}; $('#skipReviewBtn').onclick=()=>{tx.reviewed=true; tx.notes=($('#reviewNotes').value||'')+' [skipped]'; GBV.store.save(false); renderAll(); renderReview();};}
  function renderLedger(){const q=($('#ledgerSearch')?.value||'').toLowerCase(); const rows=GBV.state.transactions.filter(t=>!q||`${t.date} ${t.merchant} ${t.name} ${t.category} ${t.owner} ${t.account}`.toLowerCase().includes(q)).slice(0,500); $('#ledgerTable').innerHTML=`<table class="ledger"><thead><tr><th>Date</th><th>Merchant</th><th>Category</th><th>Owner</th><th>Amount</th><th>Status</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${escape(t.date)}</td><td><strong>${escape(t.merchant)}</strong><br><small>${escape(t.account)}</small></td><td>${escape(t.category)}</td><td>${escape(t.owner)}</td><td class="${t.amount<0?'amount-income':'amount-outflow'}">${t.amount<0?'+':'−'}${money(Math.abs(t.amount))}</td><td>${t.reviewed?'Reviewed':'Needs review'}</td></tr>`).join('')}</tbody></table>`;}
  function renderRules(){const el=$('#rulesList'); el.innerHTML=GBV.state.rules.map(r=>`<div class="list-item"><span><strong>${escape(r.match)}</strong><br><small>${escape(r.category||'No category')} • ${escape(r.owner||'No owner')}</small></span><button class="btn danger" data-remove-rule="${escape(r.id)}" type="button">Remove</button></div>`).join('')||'<p>No rules yet.</p>'; el.querySelectorAll('[data-remove-rule]').forEach(b=>b.onclick=()=>{GBV.rules.remove(b.dataset.removeRule); renderAll();});}
  function renderRoadmap(){document.getElementById('roadmapList').innerHTML=GBV.ROADMAP.map(([v,t,d])=>`<div class="roadmap-item"><span class="pill">${escape(v)}</span><h3>${escape(t)}</h3><p>${escape(d)}</p></div>`).join('');}
  function renderImportSummary(text){$('#importSummary').textContent=text||'No import yet.';}
  function renderAll(){renderDashboard(); renderLedger(); renderRules(); renderRoadmap();}
  GBV.ui={$,escape,setSection,renderDashboard,renderReview,renderLedger,renderRules,renderRoadmap,renderImportSummary,renderAll};
})();
